### ISSUE TITLE
Email or password are wrong.

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa_test#11]
Hi
on two separate machines i've tried setting up mesa_test however when running 

mesa_test install_and_test_revision HEAD $MESA_DIR --force i get 
Email or password are wrong. 

Were we meant to sign up somewhere? i thought we could just use whatever we wanted for email and password fields.

more ~/.mesa_test.yml
    ---
computer_name: stroopwafel
user_name: rfarmer
email: r.j.farmer@uva.nl
password: abcdefghijkl 
platform: debian
processor: mixed
ram_gb: 16
platform_version: '9'
compiler: SDK
compiler_version: '20171120'
last_tested: 11078

its not even tried to download mesa yet (or submit  anything back to the server) so maybe a parsing the input file issue? I've tried different emails and passwords and rerunning the setup script.

Rob

**Comment by rjfarmer** [comment]
so mesa_test install works just not mesa_test install_and_test_revision

**Comment by wmwolf** [comment]
To submit to the testhub, you need an account set up by an admin. I'll set one up for you with the username and e-mail you provided. I'll send you a temporary password as well.

Then, you need to set up your computers on the testhub. After that, you can start using mesa_test to submit results to the testhub.

If you don't have an account you can still use it to download revisions and run tests, but you need to include the --no-submit option to bypass the checks to the server.

**Comment by rjfarmer** [comment]
Thanks
