### ISSUE TITLE
`submit` fails if some tests haven't run, even though `mesa_test` recognises that they're missing

### ISSUE THREAD

**Issue by warrickball** [MESAHub/mesa_test#26]
For complicated reasons, I just ended up finishing a run of the `star` test suite but it didn't continue to `astero` and `binary`. When I try to submit the results, `mesa_test` at first appears to recognise that some results are missing but then fails, I think when it tries to find the logs:
```
$ mesa_test submit
Email, password, and computer name accepted
The following test cases could NOT be read for submission:
- double_bh
- wind_fed_bhhmxb
- star_plus_point_mass
- star_plus_point_mass_explicit_mdot
- evolve_both_stars
- jdot_ml_check
- jdot_gr_check
- jdot_ls_check
- astero_adipls
- astero_gyre
- example_astero
- surface_effects

Successfully submitted commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
Successfully submitted logs for test case dev_to_ppisn_100 in commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
Successfully submitted logs for test case c13_pocket in commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
Successfully submitted logs for test case 1.3M_ms_high_Z in commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
Successfully submitted logs for test case cburn_inward in commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
Successfully submitted logs for test case custom_rates in commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
Successfully submitted logs for test case make_co_wd in commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
Successfully submitted logs for test case ns_h in commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
/home/wball/.gem/ruby/gems/mesa_test-1.1.6/lib/mesa_test.rb:993:in `results_hash': No results found for test case double_bh. (TestCaseDirError)
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/lib/mesa_test.rb:1002:in `passed?'
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/lib/mesa_test.rb:389:in `block (2 levels) in submit_commit'
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/lib/mesa_test.rb:386:in `each'
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/lib/mesa_test.rb:386:in `block in submit_commit'
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/lib/mesa_test.rb:385:in `each'
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/lib/mesa_test.rb:385:in `submit_commit'
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/bin/mesa_test:150:in `submit'
        from /home/wball/.gem/ruby/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /home/wball/.gem/ruby/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/wball/.gem/ruby/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /home/wball/.gem/ruby/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /home/wball/.gem/ruby/gems/mesa_test-1.1.6/bin/mesa_test:407:in `<top (required)>'
        from /home/wball/bin/mesa_test:23:in `load'
        from /home/wball/bin/mesa_test:23:in `<main>'
```
The straightforward workaround is to only submit the `star` module with `mesa_test submit -m star` but it seems like `mesa_test` can work out for itself that there aren't any logs for tests that haven't run.

**Comment by wmwolf** [comment]
Did all the data get to the testhub, but then it just failed for submitting the logs for the nonexistent test? The line
```
Successfully submitted commit 4ddd47ade58a9492dcbda88b61b3381d8a668d10.
```
makes me think that the data was received by the testhub just fine. The error is annoying, I agree, and it may be the weird result of trying to submit logs for failed tests, but it couldn't determine if the untested cases were passing or not.

If it's the second case, this will probably be an easy case. If it's the first, it's more annoying.

**Comment by warrickball** [comment]
I _think_ it did successfully submit the results and logs. Have a look at any failure on `packhorse`:

https://testhub.mesastar.org/whb%2Fintrinsic-test-211006/commits/4ddd47a

so I think it's the latter case, though I possibly hadn't realised that when I opened the issue. My take is that the tests that didn't run appear to have failed but there aren't any logs to upload, which triggers the error. And I found this surprising because the first part of the output says `mesa_test` knows those tests didn't run, so I would've thought it wouldn't even try to upload logs for tests that it knows haven't run.

**Comment by wmwolf** [comment]
Ok, I've added an additional check when deciding to skip submitting the logs. It now checks to see if the testhub file even exists, and if it doesn't, it skips submitting the log.

The issue was that for each test case, `mesa_test` was checking if mesa was installed (it was), and if the test case passed (it couldn't determine this from the nonexistent `testhub.yml` file, so it errored out). If it had found the test case had passed, it would have skipped submitting the logs. Fortunately, these test cases were at the end of the line, so they shouldn't have prevented any other logs from being submitted, but this was a real problem in that if an earlier test case was skipped for some reason, later test cases would not have had their logs submitted.

It's now live in version 1.1.7, though I can't say I've done any real testing of this edge case.
