### ISSUE TITLE
Cannon reports expired certificate for logs site

### ISSUE THREAD

**Issue by evbauer** [MESAHub/mesa_test#27]
Cannon was reporting failures attempting to submit logs to logs.mesastar.org:
```
/n/home02/ebauer/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
```

I was able to force it to connect anyway by editing `submit_logs` to include
`https.verify_mode = OpenSSL::SSL::VERIFY_NONE`

But I'm not sure if this is a great long term solution. Do we need to update the logs.mesastar.org certificate somehow so that we don't continue getting these kinds of errors? Does Josiah still own that or can somebody else handle it?

Or should I submit a PR with my above line of code so that we can just default to ignoring certificate issues?

**Comment by jschwab** [comment]
I see the cert on logs.mesastar.org as valid.  I'm using LetsEncrypt with automated renewals, so there shouldn't be expiration problems (and AFAICT looking at the dates there wasn't a recent lapse).  So this is puzzling.

Here's what I see this AM in Chrome.

![screenshot-on-2021-10-09-at-09:43:18](https://user-images.githubusercontent.com/772632/136667094-f51bb19d-2e8f-4be2-8860-732583e1496f.png)

**Comment by evbauer** [comment]
Thanks! It sounds like this is probably a problem from the Cannon side then, so I won't submit a PR. I'll dig around and try to find why Cannon thinks this is expired.

**Comment by jschwab** [comment]
The following request should give you a trace

```
curl -v --header "X-Api-Key: <insert your secret API key here>" \
     --header "Content-Type: application/json" \
     --request POST \
     --data '{"computer_name":"cannon", "commit":"7a6b1c5", "test_case":"1.3M_ms_high_Z"}' \
https://logs.mesastar.org/uploads
```
and produce something like

```
*   Trying 138.68.1.113:443...
* Connected to logs.mesastar.org (138.68.1.113) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=logs.mesastar.org
*  start date: Aug 28 05:07:33 2021 GMT
*  expire date: Nov 26 05:07:32 2021 GMT
*  subjectAltName: host "logs.mesastar.org" matched cert's "logs.mesastar.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5605b0f9f9a0)
> POST /uploads HTTP/2
> Host: logs.mesastar.org
> user-agent: curl/7.79.1
> accept: */*
> x-api-key: <REDACTED>
> content-type: application/json
> content-length: 78
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 200 
< server: nginx/1.14.1
< date: Mon, 11 Oct 2021 18:24:12 GMT
< content-type: application/json
< content-length: 29
< 
{"message":"OK: Authorized"}
* Connection #0 to host logs.mesastar.org left intact
```

(Note I redacted the API key in the output.)

**Comment by evbauer** [comment]
Hmm, that doesn't complain about certificates at all. However, I can get a complaint about an expired certificate with this:
```
[ebauer@boslogin02 ~]$ openssl s_client -showcerts -connect logs.mesastar.org:443 </dev/null
CONNECTED(00000003)
depth=3 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
---
Certificate chain
 0 s:/CN=josiahschwab.com
   i:/C=US/O=Let's Encrypt/CN=R3
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
...
```

Do you know what to make of that?

**Comment by jschwab** [comment]
> Do you know what to make of that?

No and I am quite puzzled about how that request ends up leading to the cert for `josiahschwab.com` at all (let alone an expired version of it).

If you do `openssl s_client -showcerts -connect josiahschwab.com:443 </dev/null` do you also get that expired cert?

**Comment by evbauer** [comment]
Yes, I get the same message for `josiahschwab.com` as for `logs.mesastar.org`. For Cannon, that is. Running the same command on my linux box doesn't report expired certificates for either, so this seems to be dependent on openssl version (much more recent on my linux box than on Cannon).

**Comment by jschwab** [comment]
Ah, found the likely source of the issue then:

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Perhaps you can reach out the cannon admins and ask them if they have a suggested course of action.

**Comment by evbauer** [comment]
Ah, thanks! Looks like that explains it. I will check with the Cannon team to see what I can do. This should provide a very clear explanation of the issue for them to consider.
