### ISSUE TITLE
system calls using /bin/sh rather than /bin/bash

### ISSUE THREAD

**Issue by evbauer** [MESAHub/mesa_test#8]
I'm having some problems with the checksums, and I think it comes from the fact that the ruby system calls use /bin/sh on my machine. Is this nonstandard behavior? Is there something wrong with my install?

Here's the sort of thing that I'm getting in terminal output:

ERRORS
./rn: 4: ./rn: [[: not found
END OF ERRORS
appended to out.txt
./rn: 4: ./rn: [[: not found
md5sum "final.mod" > checks.md5
./re x100 >> out.txt 2> err.txt
./ck >& final_check_diff.txt
sh: 1: Syntax error: Bad fd number
******************** wd3 restart failed: checksum for final.mod does not match after ./re ************************

In particular, the last 3 lines I think are due to sh not supporting the >& syntax. The result is that the final_check_diff.txt does not get written, and so then the checksum "fails".

**Comment by wmwolf** [comment]
Uh oh, you hit on one of my fears, laid out in this comment:

````ruby
  def build_and_run
    # assumes we are in the test case directory. Should only be called
    # in the context of an `in_dir` block.

    # first clean and make... worried about shell compatibility since we
    # aren't forcing bash. Hopefully '>' for redirecting output is pretty
    # universal
    simple_clean
    mk
````

Evidently it is not, in fact, universal.

Can you see if just running $MESA_DIR/star/test_suite/each_test_run works? If it doesn't, then I'm tempted to simply not support sh on principle (in practice, we'll figure something out).

**Comment by evbauer** [comment]
I think the issue is my ruby configuration, not my shell. All the test_suite scripts have the #!/bin/bash shebang anyway, and they run fine for me. I believe the problem is that 
`system('./ck >& final_check_diff.txt')`
somehow decides to use /bin/sh due to the way ruby is configured, even though that's not my default shell. One way I've tried to deal with this problem in the past is to do this instead:
`system('bash -c "./ck >& final_check_diff.txt"')`

**Comment by wmwolf** [comment]
That's a good idea and enforces compatibility. I'll add that in and push out a new version.

That's a weird ruby bug...

**Comment by evbauer** [comment]
Also, I don't really get what the "&" part of the command is supposed to accomplish here? Maybe you could just get away with deleting that? I think just ">" would really be universal.

**Comment by wmwolf** [comment]
Lifted straight from star/test_suite/each_test_run_and_diff:

````bash
        # check that final model matches
        ./ck >& final_check_diff.txt
````
 I answer to a higher power that I assume knows better than me. It hasn't broken anything else, so I'm leaving it for now.

**Comment by evbauer** [comment]
Ok, googling around trying to understand shells better, it looks like that or `&>` will send both stderr and stdout to the file, rather than just stdout. Not supported in sh. So I guess the `bash -c` option is more robust.

**Comment by evbauer** [comment]
Ok, the bash sanitization seems to have solved my problems. No more shell issues during my most recent run.
